name: idp_new
channels:
  - defaults
dependencies:
  - matplotlib=2.1.0
  - patsy=0.5.0
  - seaborn=0.9.0
  - tqdm=4.24.0
  - ipython
  - jupyter
  - notebook
  - numpy=1.14.3
  - pandas=0.23.0
  - python=3.6
  - scikit-learn=0.19.1
  - scipy=1.1.0
  - setuptools
  - cython
  - mkl-service
  - pip:
    - cobra==0.12.1
    - pymc3==3.5
    - swiglpk==1.4.4
    - theano==1.0.3
